/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef GAMEPAD_AUTODEFS_H
#define GAMEPAD_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GAMEPAD_NAME "gamepad"
#define S3E_EXT_GAMEPAD_HASH 0xe6a02e94

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("gamepad", 11)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !GAMEPAD_AUTODEFS_H */
