/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_JOYSTICK_H
#define S3E_EXT_JOYSTICK_H

#include <s3eTypes.h>

struct JoystickData {
  long mAnalogueInputs[8];
  unsigned long mPOVDirections[4];
  unsigned char mButtons[128];
  char mName[512];
};
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the Joystick extension is available.
 */
s3eBool JoystickAvailable();

s3eResult GetJoystickStatus(JoystickData& joystick, int id);

void CalibrateJoystick();

S3E_END_C_DECL

#endif /* !S3E_EXT_JOYSTICK_H */
