/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef DPIEXT_AUTODEFS_H
#define DPIEXT_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_DPIEXT_NAME "dpiExt"
#define S3E_EXT_DPIEXT_HASH 0xf948ed73

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("dpiExt", 1)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !DPIEXT_AUTODEFS_H */
