/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef        int(*dpiExtGetDeviceDPI_t)();

/**
 * struct that gets filled in by dpiExtRegister
 */
typedef struct dpiExtFuncs
{
    dpiExtGetDeviceDPI_t m_dpiExtGetDeviceDPI;
} dpiExtFuncs;
