 #ifndef GAMEPAD_INTERFACE_H
 #define GAMEPAD_INTERFACE_H

/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
#include <cstdint>

typedef     uint32_t(*gamepadGetNumDevices_t)();
typedef     uint32_t(*gamepadGetDeviceId_t)(uint32_t index);
typedef     uint32_t(*gamepadGetNumAxes_t)(uint32_t index);
typedef     uint32_t(*gamepadGetNumButtons_t)(uint32_t index);
typedef     uint32_t(*gamepadGetButtons_t)(uint32_t index);
typedef      int32_t(*gamepadGetAxis_t)(uint32_t index, uint32_t axisIndex);
typedef     uint32_t(*gamepadIsPointOfViewAvailable_t)(uint32_t index);
typedef      int32_t(*gamepadGetPointOfViewAngle_t)(uint32_t index);
typedef       void(*gamepadUpdate_t)();
typedef       void(*gamepadReset_t)();
typedef       void(*gamepadCalibrate_t)();

/**
 * struct that gets filled in by gamepadRegister
 */
typedef struct gamepadFuncs
{
    gamepadGetNumDevices_t m_gamepadGetNumDevices;
    gamepadGetDeviceId_t m_gamepadGetDeviceId;
    gamepadGetNumAxes_t m_gamepadGetNumAxes;
    gamepadGetNumButtons_t m_gamepadGetNumButtons;
    gamepadGetButtons_t m_gamepadGetButtons;
    gamepadGetAxis_t m_gamepadGetAxis;
    gamepadIsPointOfViewAvailable_t m_gamepadIsPointOfViewAvailable;
    gamepadGetPointOfViewAngle_t m_gamepadGetPointOfViewAngle;
    gamepadUpdate_t m_gamepadUpdate;
    gamepadReset_t m_gamepadReset;
    gamepadCalibrate_t m_gamepadCalibrate;
} gamepadFuncs;


#endif