/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef JOYSTICK_AUTODEFS_H
#define JOYSTICK_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_JOYSTICK_NAME "Joystick"
#define S3E_EXT_JOYSTICK_HASH 0xd21864b5

#endif /* !JOYSTICK_AUTODEFS_H */
